CREATE TABLE customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  document_type VARCHAR(30) NOT NULL,
  document_number VARCHAR(40) NOT NULL,
  name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(160) NULL,
  address VARCHAR(255) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_document UNIQUE (document_type, document_number),
  CONSTRAINT uk_customer_email UNIQUE (email)
);




