CREATE TABLE permission (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(255) NULL,
  action VARCHAR(80) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_permission_name_action UNIQUE (name, action)
);



