CREATE TABLE module (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  base_path VARCHAR(160) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_module_name UNIQUE (name),
  CONSTRAINT uk_module_base_path UNIQUE (base_path)
);



