CREATE TABLE screen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  module_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(255) NULL,
  path VARCHAR(180) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_screen_module_path UNIQUE (module_id, path),
  CONSTRAINT fk_screen_module FOREIGN KEY (module_id) REFERENCES module (id)
);



