CREATE TABLE app_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  person_id BIGINT NOT NULL,
  username VARCHAR(80) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  last_access_at TIMESTAMP NULL,
  blocked BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_app_user_person UNIQUE (person_id),
  CONSTRAINT uk_app_user_username UNIQUE (username),
  CONSTRAINT fk_app_user_person FOREIGN KEY (person_id) REFERENCES person (id)
);



