CREATE TABLE app_user_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  app_user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_app_user_role UNIQUE (app_user_id, role_id),
  CONSTRAINT fk_app_user_role_app_user FOREIGN KEY (app_user_id) REFERENCES app_user (id),
  CONSTRAINT fk_app_user_role_app_role FOREIGN KEY (role_id) REFERENCES app_role (id)
);



