CREATE TABLE module_screen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  module_id BIGINT NOT NULL,
  screen_id BIGINT NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_module_screen UNIQUE (module_id, screen_id),
  CONSTRAINT fk_module_screen_module FOREIGN KEY (module_id) REFERENCES module (id),
  CONSTRAINT fk_module_screen_screen FOREIGN KEY (screen_id) REFERENCES screen (id)
);



