CREATE TABLE room_maintenance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_id BIGINT NOT NULL,
  employee_id BIGINT NULL,
  maintenance_type VARCHAR(60) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NULL,
  maintenance_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  note TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_room_maintenance FOREIGN KEY (room_id) REFERENCES room (id),
  CONSTRAINT fk_maintenance_employee FOREIGN KEY (employee_id) REFERENCES employee (id)
);

CREATE INDEX ix_room_maintenance ON room_maintenance (room_id, start_date, end_date);
CREATE INDEX ix_maintenance_employee ON room_maintenance (employee_id);




