CREATE TABLE maintenance_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_maintenance_id BIGINT NOT NULL,
  usage_reason VARCHAR(160) NOT NULL,
  activity_detail TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_maintenance_usage UNIQUE (room_maintenance_id),
  CONSTRAINT fk_maintenance_usage_base FOREIGN KEY (room_maintenance_id) REFERENCES room_maintenance (id)
);



