CREATE TABLE maintenance_remodeling (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_maintenance_id BIGINT NOT NULL,
  remodeling_description TEXT NOT NULL,
  estimated_budget DECIMAL(12,2) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_maintenance_remodeling UNIQUE (room_maintenance_id),
  CONSTRAINT fk_maintenance_remodeling_base FOREIGN KEY (room_maintenance_id) REFERENCES room_maintenance (id),
  CONSTRAINT ck_maintenance_budget CHECK (estimated_budget IS NULL OR estimated_budget >= 0)
);




