CREATE TABLE legal_information (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  company_id BIGINT NOT NULL,
  legal_document_type VARCHAR(80) NOT NULL,
  legal_document_number VARCHAR(80) NOT NULL,
  description TEXT NULL,
  issue_date DATE NULL,
  expiration_date DATE NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_legal_information_company FOREIGN KEY (company_id) REFERENCES company (id)
);

CREATE INDEX ix_legal_information_company ON legal_information (company_id);



