CREATE TABLE employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  person_id BIGINT NOT NULL,
  job_title VARCHAR(100) NOT NULL,
  hire_date DATE NOT NULL,
  work_phone VARCHAR(40) NULL,
  work_email VARCHAR(160) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_employee_person UNIQUE (person_id),
  CONSTRAINT uk_employee_work_email UNIQUE (work_email),
  CONSTRAINT fk_employee_person FOREIGN KEY (person_id) REFERENCES person (id)
);



