CREATE TABLE product_tracking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NOT NULL,
  movement_type VARCHAR(40) NOT NULL,
  quantity INTEGER NOT NULL,
  movement_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_product_tracking FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT ck_tracking_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_product_tracking ON product_tracking (product_id, movement_at);




