CREATE TABLE inventory_availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT NULL,
  service_id BIGINT NULL,
  available_quantity INT NOT NULL DEFAULT 0,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  note VARCHAR(255) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_availability_inventory_product FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT fk_availability_inventory_service FOREIGN KEY (service_id) REFERENCES service (id),
  CONSTRAINT ck_availability_inventory_item CHECK (product_id IS NOT NULL OR service_id IS NOT NULL),
  CONSTRAINT ck_availability_inventory_quantity CHECK (available_quantity >= 0)
);

CREATE INDEX ix_availability_inventory_product ON inventory_availability (product_id);
CREATE INDEX ix_availability_inventory_service ON inventory_availability (service_id);




