CREATE TABLE product_sale (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  stay_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_amount DECIMAL(12,2) NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_product_sale_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT fk_product_sale_product FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT ck_product_sale_values CHECK (quantity > 0 AND unit_amount >= 0 AND total_amount >= 0)
);

CREATE INDEX ix_product_sale_stay ON product_sale (stay_id);
CREATE INDEX ix_product_sale_product ON product_sale (product_id);




