CREATE TABLE service_sale (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  stay_id BIGINT NOT NULL,
  service_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_amount DECIMAL(12,2) NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_service_sale_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT fk_service_sale_service FOREIGN KEY (service_id) REFERENCES service (id),
  CONSTRAINT ck_service_sale_values CHECK (quantity > 0 AND unit_amount >= 0 AND total_amount >= 0)
);

CREATE INDEX ix_service_sale_stay ON service_sale (stay_id);
CREATE INDEX ix_service_sale_service ON service_sale (service_id);




