CREATE TABLE pre_invoice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  stay_id BIGINT NOT NULL,
  room_reservation_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_pre_invoice_stay UNIQUE (stay_id),
  CONSTRAINT fk_pre_invoice_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT fk_pre_invoice_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT fk_pre_invoice_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT ck_pre_invoice_values CHECK (subtotal >= 0 AND tax_amount >= 0 AND discount_amount >= 0 AND total >= 0)
);

CREATE INDEX ix_pre_invoice_reservation ON pre_invoice (room_reservation_id);
CREATE INDEX ix_pre_invoice_customer ON pre_invoice (customer_id);




