CREATE TABLE invoice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  stay_id BIGINT NOT NULL,
  invoice_number VARCHAR(60) NOT NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  invoice_status VARCHAR(40) NOT NULL DEFAULT 'ISSUED',
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_invoice_number UNIQUE (invoice_number),
  CONSTRAINT uk_invoice_stay UNIQUE (stay_id),
  CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT fk_invoice_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT ck_invoice_values CHECK (subtotal >= 0 AND tax_amount >= 0 AND discount_amount >= 0 AND total >= 0)
);

CREATE INDEX ix_invoice_customer ON invoice (customer_id);




