CREATE TABLE partial_payment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_reservation_id BIGINT NULL,
  invoice_id BIGINT NULL,
  payment_method_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payment_reference VARCHAR(120) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_payment_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id),
  CONSTRAINT fk_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_method (id),
  CONSTRAINT ck_payment_amount CHECK (amount > 0),
  CONSTRAINT ck_payment_source CHECK (room_reservation_id IS NOT NULL OR invoice_id IS NOT NULL)
);

CREATE INDEX ix_payment_reservation ON partial_payment (room_reservation_id);
CREATE INDEX ix_payment_invoice ON partial_payment (invoice_id);
CREATE INDEX ix_payment_method ON partial_payment (payment_method_id);




