CREATE TABLE purchase_detail (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  invoice_id BIGINT NOT NULL,
  product_id BIGINT NULL,
  service_id BIGINT NULL,
  description VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  unit_amount DECIMAL(12,2) NOT NULL,
  total_amount DECIMAL(12,2) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_detail_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id),
  CONSTRAINT fk_detail_product FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT fk_detail_service FOREIGN KEY (service_id) REFERENCES service (id),
  CONSTRAINT ck_detail_values CHECK (quantity > 0 AND unit_amount >= 0 AND total_amount >= 0),
  CONSTRAINT ck_detail_item CHECK (product_id IS NOT NULL OR service_id IS NOT NULL)
);

CREATE INDEX ix_detail_invoice ON purchase_detail (invoice_id);
CREATE INDEX ix_detail_product ON purchase_detail (product_id);
CREATE INDEX ix_detail_service ON purchase_detail (service_id);




