CREATE TABLE day_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  date DATE NULL,
  applies_season BOOLEAN NOT NULL DEFAULT FALSE,
  applies_holiday BOOLEAN NOT NULL DEFAULT FALSE,
  applies_special_day BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_day_type_name_date UNIQUE (name, date)
);



