CREATE TABLE room_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  base_capacity SMALLINT NOT NULL,
  max_capacity SMALLINT NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_room_type_name UNIQUE (name),
  CONSTRAINT ck_room_type_capacity CHECK (max_capacity >= base_capacity)
);



