CREATE TABLE room_status (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  allows_reservation BOOLEAN NOT NULL DEFAULT FALSE,
  allows_check_in BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_room_status_name UNIQUE (name)
);



