CREATE TABLE price (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_type_id BIGINT NOT NULL,
  day_type_id BIGINT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NULL,
  condition VARCHAR(255) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_price_day_type_inicio UNIQUE (room_type_id, day_type_id, start_date),
  CONSTRAINT fk_price_room_type FOREIGN KEY (room_type_id) REFERENCES room_type (id),
  CONSTRAINT fk_price_day_type FOREIGN KEY (day_type_id) REFERENCES day_type (id),
  CONSTRAINT ck_price_amount CHECK (amount >= 0)
);

CREATE INDEX ix_price_room_type ON price (room_type_id);
CREATE INDEX ix_price_day_type ON price (day_type_id);



