CREATE TABLE room_reservation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  guest_count SMALLINT NOT NULL,
  reservation_status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  estimated_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_reservation_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT fk_room_reservation FOREIGN KEY (room_id) REFERENCES room (id),
  CONSTRAINT ck_reservation_dates CHECK (end_date > start_date)
);

CREATE INDEX ix_reservation_customer ON room_reservation (customer_id);
CREATE INDEX ix_room_reservation_date ON room_reservation (room_id, start_date, end_date);




