CREATE TABLE room_cancellation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_reservation_id BIGINT NOT NULL,
  reason VARCHAR(255) NOT NULL,
  cancelled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  applies_penalty BOOLEAN NOT NULL DEFAULT FALSE,
  penalty_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_cancellation_reservation UNIQUE (room_reservation_id),
  CONSTRAINT fk_cancellation_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT ck_cancellation_penalty CHECK (penalty_amount >= 0)
);



