CREATE TABLE room_availability (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_id BIGINT NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  unavailable_reason VARCHAR(255) NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_room_availability FOREIGN KEY (room_id) REFERENCES room (id),
  CONSTRAINT ck_availability_dates CHECK (end_date > start_date)
);

CREATE INDEX ix_room_availability_date ON room_availability (room_id, start_date, end_date);




