CREATE TABLE room_catalog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_id BIGINT NOT NULL,
  title VARCHAR(160) NOT NULL,
  description TEXT NULL,
  base_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_room_catalog UNIQUE (room_id),
  CONSTRAINT fk_room_catalog FOREIGN KEY (room_id) REFERENCES room (id),
  CONSTRAINT ck_catalog_price CHECK (base_price >= 0)
);




