CREATE TABLE stay (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_reservation_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NULL,
  stay_status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_stay_reservation UNIQUE (room_reservation_id),
  CONSTRAINT fk_stay_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT fk_stay_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT fk_stay_room FOREIGN KEY (room_id) REFERENCES room (id)
);

CREATE INDEX ix_stay_customer ON stay (customer_id);
CREATE INDEX ix_stay_room ON stay (room_id);




