CREATE TABLE check_in (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  room_reservation_id BIGINT NOT NULL,
  employee_id BIGINT NOT NULL,
  checked_in_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_check_in_reservation UNIQUE (room_reservation_id),
  CONSTRAINT fk_check_in_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id),
  CONSTRAINT fk_check_in_employee FOREIGN KEY (employee_id) REFERENCES employee (id)
);

CREATE INDEX ix_check_in_employee ON check_in (employee_id);




