CREATE TABLE check_out (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  stay_id BIGINT NOT NULL,
  employee_id BIGINT NOT NULL,
  checked_out_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note TEXT NULL,
  total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_check_out_stay UNIQUE (stay_id),
  CONSTRAINT fk_check_out_stay FOREIGN KEY (stay_id) REFERENCES stay (id),
  CONSTRAINT fk_check_out_employee FOREIGN KEY (employee_id) REFERENCES employee (id),
  CONSTRAINT ck_check_out_amount CHECK (total_amount >= 0)
);

CREATE INDEX ix_check_out_employee ON check_out (employee_id);



