CREATE TABLE promotion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(160) NOT NULL,
  description TEXT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NULL,
  channel VARCHAR(60) NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id)
);

CREATE INDEX ix_promotion_date ON promotion (start_date, end_date);



