CREATE TABLE alert (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NULL,
  room_reservation_id BIGINT NULL,
  title VARCHAR(160) NOT NULL,
  mensaje TEXT NOT NULL,
  channel VARCHAR(60) NOT NULL,
  sent_at TIMESTAMP NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT fk_alert_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT fk_alert_reservation FOREIGN KEY (room_reservation_id) REFERENCES room_reservation (id)
);

CREATE INDEX ix_alert_customer ON alert (customer_id);
CREATE INDEX ix_alert_reservation ON alert (room_reservation_id);




