CREATE TABLE customer_loyalty (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id BIGINT NOT NULL,
  level VARCHAR(60) NOT NULL DEFAULT 'BASIC',
  points INTEGER NOT NULL DEFAULT 0,
  last_interaction_at TIMESTAMP NULL,
  note TEXT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL,
  deleted_by BIGINT NULL,
  deleted_at TIMESTAMP NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  CONSTRAINT uk_customer_loyalty UNIQUE (customer_id),
  CONSTRAINT fk_customer_loyalty FOREIGN KEY (customer_id) REFERENCES customer (id)
);



